### ISSUE TITLE
TypeError: setRange(self, min: int, max: int): argument 2 has unexpected type 'float'

### ISSUE THREAD

**Issue by mriamnobody** [iGio90/Dwarf#104]
When I start dwarf, I get the following error:

```
Traceback (most recent call last):
  File "C:\Users\rosha\Downloads\Compressed\frida\frida\lib\site-packages\dwarf_debugger\ui\app.py", line 723, in session_created
    self._create_ui_elem(ui_elem)
  File "C:\Users\rosha\Downloads\Compressed\frida\frida\lib\site-packages\dwarf_debugger\ui\app.py", line 514, in _create_ui_elem
    self.debug_panel = QDebugPanel(self)
  File "C:\Users\rosha\Downloads\Compressed\frida\frida\lib\site-packages\dwarf_debugger\ui\panels\panel_debug.py", line 26, in __init__
    self.memory_panel = HexEditor(self.app)
  File "C:\Users\rosha\Downloads\Compressed\frida\frida\lib\site-packages\dwarf_debugger\ui\widgets\hex_edit.py", line 258, in __init__
    self.adjust()
  File "C:\Users\rosha\Downloads\Compressed\frida\frida\lib\site-packages\dwarf_debugger\ui\widgets\hex_edit.py", line 614, in adjust
    self.horizontalScrollBar().setRange(0,self.number_of_chars() - self.visible_columns() + 1)
TypeError: setRange(self, min: int, max: int): argument 2 has unexpected type 'float'
```

I used the following commands to start Dwarf:

1) By using plain command `dwarf` in command prompt.
2) By using command `dwarf -t android com.xyz.xyz`

In the first case, a GUI opens where I get the option to click on a different platform. When I click any of the platforms I get the above error. In the second case before the error appears the following text is printed on the console:

`Updating local frida version to 16.0.19
failed to update local frida
ERROR: Can not perform a '--user' install. User site-packages are not visible in this virtualenv.`

**Desktop (please complete the following information):**
 - Windows 11
 - Python 3.10.7

**Smartphone (please complete the following information):**
 - Oneplus 6
 - Android 12
 - Stock browser

**Comment by PinkiePieStyle** [comment]
#95 fixed with 944628dfd9e8b9b6cee8807a4384acccd4e63349
