### ISSUE TITLE
Not able to run Dwarf

### ISSUE THREAD

**Issue by folkene** [iGio90/Dwarf#15]
Hello,

I just find out about your tool, it looks amazing for reverser. Unfortunately I'm not able to start it.

I get the error : 
Traceback (most recent call last):
  File "dwarf.py", line 26, in <module>
    from ui.app import AppWindow
  File "/Users/esoussi/work/util/Dwarf/ui/app.py", line 23, in <module>
    from lib.core import Dwarf
  File "/Users/esoussi/work/util/Dwarf/lib/core.py", line 28, in <module>
    from lib.emulator import Emulator
  File "/Users/esoussi/work/util/Dwarf/lib/emulator.py", line 24, in <module>
    from capstone import *
  File "/usr/local/lib/python3.7/site-packages/capstone/__init__.py", line 406, in <module>
    _setup_prototype(_cs, "cs_regs_access", ctypes.c_int, ctypes.c_size_t, ctypes.POINTER(_cs_insn), ctypes.POINTER(ctypes.c_uint16*64), ctypes.POINTER(ctypes.c_uint8), ctypes.POINTER(ctypes.c_uint16*64), ctypes.POINTER(ctypes.c_uint8))
  File "/usr/local/lib/python3.7/site-packages/capstone/__init__.py", line 388, in _setup_prototype
    getattr(lib, fname).restype = restype
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ctypes/__init__.py", line 369, in __getattr__
    func = self.__getitem__(name)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ctypes/__init__.py", line 374, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(0x7fe3462e5a60, cs_regs_access): symbol not found

For information, I'm using MacOs.

Thanks for the support.

**Comment by iGio90** [comment]
this is capstone!

did you
```
brew install capstone
pip3 install capstone
```
??

**Comment by iGio90** [comment]
also, consider using branch dev with the new UI and features as I'll soon merge it into master and eventual bug which pop would be fixed before!

I had really poor free time in the past months so hopefully i'll get back into it very shortly

**Comment by folkene** [comment]
Hello,
Yes I did install capstone :).
Using the dev branch, the issue is still present :(.

Thanks for the reply anyway.

**Comment by folkene** [comment]
Just for info, I finally found the issue : I had two version of capstone... After removing the older one, I made it to work.

Thanks for the support :)
