### ISSUE TITLE
No module

### ISSUE THREAD

**Issue by Chensem** [iGio90/Dwarf#21]
```
% python3 dwarf.py
Traceback (most recent call last):
  File "dwarf.py", line 26, in <module>
    from ui.app import AppWindow
  File "/Users/whoami/Program/Dwarf/ui/app.py", line 32, in <module>
    from ui.hex_edit import HighLight, HighlightExistsError
  File "/Users/whoami/Program/Dwarf/ui/hex_edit.py", line 29, in <module>
    from lib.elf import ELF
ModuleNotFoundError: No module named 'lib.elf'
```

**Comment by iGio90** [comment]
5:30 am, thanks for giving me a good reason to jump from the bad XD

**Comment by Chensem** [comment]
thanks ! XD
