### ISSUE TITLE
The 'PyQt5==5.11.3' distribution was not found and is required by dwarf

### ISSUE THREAD

**Issue by linxon** [iGio90/Dwarf#43]
Is it really necessary to tightly bind the version? I have PyQt5-5.13.0 but I get this error:

```python
linxon@minako-chan /tmp/linxon-tmp-files $ dwarf 
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    ws.require(__requires__)
  File "/usr/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 898, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 789, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (PyQt5 5.13.0 (/usr/lib64/python3.6/site-packages), Requirement.parse('PyQt5==5.11.3'), {'dwarf'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.6/dwarf", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 3126, in <module>
    @_call_aside
  File "/usr/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 3110, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 3139, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 596, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 784, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'PyQt5==5.11.3' distribution was not found and is required by dwarf
```

**Comment by iGio90** [comment]
Is it working fine with ur pyqt?

**Comment by linxon** [comment]
>Is it working fine with ur pyqt?
```python
pkg_resources.ContextualVersionConflict: (PyQt5 5.13.0 (/usr/lib64/python3.6/site-packages), Requirement.parse('PyQt5==5.11.3'), {'dwarf'})
```

**Comment by linxon** [comment]
https://github.com/iGio90/Dwarf/blob/a42b9188843fb31177e73b3eac76750073eab1ed/setup.py#L42-L45

do you can change `==` to `>=` ?

**Comment by iGio90** [comment]
guess it should works fine now? there was a typo in requirements and some other small things around

**Comment by linxon** [comment]
I just tried to changing setup.py file as:
```diff
 install_requires=[ 
-     'capstone==4.0.1', 'requests==2.22.0', 'frida==12.6.11', 
-     'PyQt5==5.11.3', 'pyperclip==1.7.0' 
+     'capstone>=4.0.1', 'requests>=2.22.0', 'frida>=12.6.11',
+     'PyQt5>=5.11.3', 'pyperclip>=1.7.0' 
 ], 
```

 and this allowed me to run your program with installed `PyQt5-5.13.0` on my system. Your program really required only `PyQt5==5.11.3` version?

P.S.
sorry for my fucking English **.**

**Comment by iGio90** [comment]
No it doesnt. It should properly work also with 5.13!

Your english is fine :)

**Comment by iGio90** [comment]
I've replaced with your code! Thanks
