### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by resonance00x0** [iGio90/Dwarf#77]
The application crashes when any of the button from launcher window clicked 
```
Traceback (most recent call last):
  File "/home/ajk/tools/Dwarf/dwarf_debugger/ui/app.py", line 693, in session_created
    self._create_ui_elem(ui_elem)
  File "/home/ajk/tools/Dwarf/dwarf_debugger/ui/app.py", line 507, in _create_ui_elem
    self.console_panel = ConsoleWidget(self)
  File "/home/ajk/tools/Dwarf/dwarf_debugger/ui/session_widgets/console.py", line 29, in __init__
    self.js_console = DwarfConsoleWidget(parent, input_placeholder='$>', function_box=True)
  File "/home/ajk/tools/Dwarf/dwarf_debugger/ui/widgets/widget_console.py", line 117, in __init__
    self.input = DwarfConsoleInput(self, completer=completer)
  File "/home/ajk/tools/Dwarf/dwarf_debugger/ui/widgets/widget_console.py", line 35, in __init__
    super().__init__(parent=parent, completer=completer)
  File "/home/ajk/tools/Dwarf/dwarf_debugger/ui/widgets/code_editor.py", line 390, in __init__
    self.setTabStopDistance(self.fontMetrics().width('9999'))
AttributeError: 'DwarfConsoleInput' object has no attribute 'setTabStopDistance'
```

**Comment by PinkiePieStyle** [comment]
PyQt5>=5.11.3

**Comment by resonance00x0** [comment]
Thank you
